version: "3.9"

services:
  geth:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./execution:/root/.ethereum
      - ./jwtsecret:/root/.ethereum/jwtsecret
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
      - "30303:30303/udp"

  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command:
      - --datadir=/consensus/beacondata
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/root/.ethereum/jwtsecret
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --p2p-host-ip=0.0.0.0
      - --chain-id=787878
      - --accept-terms-of-use
      - --grpc-gateway-port=3500
      - --min-sync-peers=1
      - --bootstrap-node=enr:-Ke4QIUKE3dltAD5SgDJzWlQ_fCcQbP06GFL-FPufWNKH9syBPaRD6cIkncjFduAn7m0AuEBzKZeJPCwMuD59e5TlEaGAZCXXEiHg2V0aMvKhD4l0bqEZr6CAoJpZIJ2NIJpcIR_AAABiXNlY3AyNTZrMaECHUiUuz_KqJOsd0_mIBJcR71OnZdY-4GvIVix-7QkTA6Ec25hcMCDdGNwgnZfg3VkcIJ2Xw
    ports:
      - "3500:3500"
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - ./consensus:/consensus
      - ./jwtsecret:/root/.ethereum/jwtsecret
    depends_on:
      - geth

volumes:
  execution:
  consensus:
